name: trakify
description: "Habit tracking app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # For Saving Data Locally in cache
  shared_preferences: ^2.5.3
  # For Responsive UI
  flutter_screenutil: ^5.9.3
  # Customizable animated page indicator
  smooth_page_indicator: ^1.2.1
  # For dependency injection
  get_it: ^8.0.3
  # For lancher icon
  flutter_launcher_icons: ^0.14.3
  # Customize Flutter splash screen
  flutter_native_splash: ^2.4.6
  # For Translation and Localization
  intl: ^0.19.0
  # State management
  flutter_bloc: ^9.1.0
  # For animation Images
  lottie: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4
  animated_bottom_navigation_bar: ^1.4.0
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.3
  image_picker: ^1.1.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1



flutter_launcher_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/images/icon/app_icon.png"
  adaptive_icon_background: "#1D8466"
  remove_alpha_ios: true
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: any


flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/onboarding/
    - assets/images/logo/
    - assets/images/icon/
    - assets/images/shapes/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/IBMPlexSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
          weight: 700
          style: italic

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart
  field_prefix: null

flutter_intl:
  enabled: true
